// src/components/Nonogram.tsx
import * as React from "react";
import { Nonogram, SolvedNonogram } from "../lib/solver";

export type CellClickedHandler = (x: number, y: number) => Promise<void>;
export interface NonogramInput {
	input: Nonogram,
	filled: SolvedNonogram,
    cellClicked: CellClickedHandler,
};

type ME = React.MouseEvent<HTMLElement, MouseEvent>;
type CellProps = { 
    x: number, 
    y: number, 
    filled: boolean[][],
    cellClicked: CellClickedHandler
};

const isPrimaryButtonClicked = (event: ME) => (event.buttons & 1) === 1;
function createCellMouseEnterHandler({ x, y, cellClicked }: CellProps) {
    return async (event: ME) => {
        if (!isPrimaryButtonClicked(event))
            return;

        if (cellClicked)
            await cellClicked(x, y);
    }
}

function Cell(props: CellProps) {
    const value = props.filled[props.x][props.y];
    return (
        <td
            style={{
                background: value ? "black" : "gray"
            }}
            onMouseEnter={createCellMouseEnterHandler(props)}
            onMouseDown={createCellMouseEnterHandler(props)}
        >
            {value}
        </td>
    )
}

export default (({ filled, input, cellClicked }: NonogramInput) => {
	const getHighestStack = (n: number[][]) =>
		Math.max(...n.map((s) => s.length));
	const highestStackBottom = getHighestStack(input.bottom),
		highestStackRight = getHighestStack(input.right);

	return (
		<table>
            <tbody>
                {Array.from({ length: highestStackBottom }, (_, i) => (
                    <tr>
                        {<td key={`e${i}`} colSpan={highestStackRight}></td>}
                        {input.bottom.map((ns, idx) => {
                            // TODO: If array is empty, insert content placeholder to ensure width
                            const offset = highestStackBottom - ns.length;
                            const n = offset <= i ? ns[i - offset] : null;
                            return <td key={`t${i}.${idx}`}>{n}</td>;
                        })}
                    </tr>
                ))}

                {Array.from({ length: input.right.length }, (_, y) => (
                    <tr>
                        {Array.from(
                            { length: highestStackRight - input.right[y].length },
                            (_, idx) => (
                                <td key={`e${y}.${idx}`}></td>
                            ),
                        )}
                        {
                            // TODO: If array is empty, insert content placeholder to ensure height
                            input.right[y].map((n) => {
                                return <td>{n}</td>;
                            })
                        }
                        {Array.from({ length: input.bottom.length }, (_, x) => 
                            <Cell x={y} y={x} filled={filled.cells} cellClicked={cellClicked} />
                        )}
                    </tr>
                ))}
            </tbody>
		</table>
	);
});

// src/lib/components/Nonogram.svelte
<script lang="ts">
	import type { Nonogram, SolvedNonogram } from '$lib/solver';
	import { PALETTE } from '$lib/storable';
	import { getPalleteClasses } from '$lib/util';

	const { nonogram, filled, cellClicked }: Props = $props();

	type Props = {
		nonogram: Nonogram;
		filled: SolvedNonogram;
		cellClicked: CellClickedHandler;
	};
	type CellClickedHandler = (x: number, y: number) => Promise<void>;

	type CellProps = {
		x: number;
		y: number;
	};
	const isPrimaryButtonClicked = (event: MouseEvent) => (event.buttons & 1) === 1;
	const mouseEventHandler = ({ x, y }: CellProps) => {
		return async (event: MouseEvent) => {
			if (!isPrimaryButtonClicked(event)) return;

			if (cellClicked) await cellClicked(x, y);
		};
	};

	const baseCellClasses = $derived({
		'size-6': true,
		'text-center': true,
		border: true,
		...getPalleteClasses($PALETTE, 'border', 300, 500)
	});

	const getHighestStack = (n: number[][]) => Math.max(...n.map((s) => s.length));
	const highestStackHorizontal = $derived(getHighestStack(nonogram.horizontal)),
		highestStackVertical = $derived(getHighestStack(nonogram.vertical));
</script>

<table class="m-1">
	<tbody>
		{#each Array.from({ length: highestStackHorizontal }) as _, y}
			<tr>
				{#if y === 0}
					<td
						colspan={highestStackVertical}
						rowspan={highestStackHorizontal}
						class={{
							...baseCellClasses,
							...getPalleteClasses($PALETTE, 'bg', 50)
						}}
					></td>
				{/if}
				{#each nonogram.horizontal as stack}
					{@const offset = highestStackHorizontal - stack.length}
					{@const n = offset <= y ? stack[y - offset] : null}
					<td
						class={{
							...baseCellClasses,
							...getPalleteClasses($PALETTE, 'bg', 100)
						}}>{n}</td
					>
				{/each}
			</tr>
		{/each}
		{#each Array.from({ length: nonogram.vertical.length }) as _, y}
			<tr>
				{#each Array.from({ length: highestStackVertical - nonogram.vertical[y].length }) as _, y}
					<td
						class={{
							...baseCellClasses,
							...getPalleteClasses($PALETTE, 'bg', 100)
						}}
					></td>
				{/each}
				{#each nonogram.vertical[y] as n}
					<td
						class={{
							...baseCellClasses,
							...getPalleteClasses($PALETTE, 'bg', 100)
						}}>{n}</td
					>
				{/each}
				{#each Array.from({ length: nonogram.horizontal.length }) as _, x}
					{@const f = filled.cells[x][y]}
					<td
						onmouseenter={mouseEventHandler({ x, y })}
						onmousedown={mouseEventHandler({ x, y })}
						class={{
							...baseCellClasses,
							...getPalleteClasses($PALETTE, 'bg', 700, 700, f),
							...getPalleteClasses($PALETTE, 'bg', 200, 200, !f),
							'select-none': true
						}}
					></td>
				{/each}
			</tr>
		{/each}
	</tbody>
</table>
